### ISSUE TITLE
issue when mounting the fs

### ISSUE THREAD

**Issue by Billos** [EnigmaCurry/GMusicFS#13]
Hello, 
I managed to install fusepy, gmusicapi and GMusicFS

But when I try to mount the google music fs, I have this issue : 

[root@alarmpi bin]# gmusicfs /media/music/brendan/
Traceback (most recent call last):
  File "/usr/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.3/site-packages/pkg_resources.py", line 2108, in load
    entry = **import**(self.module_name, globals(),globals(), ['**name**'])
  File "/usr/lib/python3.3/site-packages/gmusicfs/gmusicfs.py", line 229
    'st_mode' : (S_IFDIR |0755),
                             ^
SyntaxError: invalid token

**Comment by EnigmaCurry** [comment]
Try it with python 2.7

**Comment by Billos** [comment]
I'm not a python developper, how should I use this version ?

**Comment by Billos** [comment]
Ok, I tried to use python2.7

[root@alarmpi bin]# gmusicfs /media/music/brendan/
Traceback (most recent call last):
  File "/usr/bin/gmusicfs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2793, in <module>
    working_set.require(**requires**)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: GMusicFS==0.1

**Comment by EnigmaCurry** [comment]
Try reinstalling it with a 2.7 version of pip (probably called pip-2.7)

**Comment by Billos** [comment]
Ok, this worked !
Thank you very much.

**Comment by EnigmaCurry** [comment]
No prob
