### ISSUE TITLE
cannot mount file system

### ISSUE THREAD

**Issue by slifin** [EnigmaCurry/GMusicFS#26]
gmusicfs ~/music
Traceback (most recent call last):
  File "/usr/local/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 452, in main
    fs = GMusicFS(mountpoint, true_file_size=args.true_file_size, verbose=verbosity)
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 229, in **init**
    true_file_size=true_file_size, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 132, in **init**
    self.rescan()
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 138, in rescan
    self.__aggregate_albums()
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 172, in __aggregate_albums
    tracks = self.api.get_all_songs()
AttributeError: 'Webclient' object has no attribute 'get_all_songs'

**Comment by jpenguin** [comment]
Same error on Kubunntu 14.04 & OSX 10.9.2 & OpenSUSE

**Comment by jpenguin** [comment]
Fails on fedora (output with -vv)
https://gist.github.com/jpenguin/faaee0f06d6d2e3f832f

**Comment by synthVerity** [comment]
Same problem on Debian Wheezy.

**Comment by mrdrogdrog** [comment]
Same error on Ubuntu 14.
Seems like the GMusicApi changed.

**Comment by rjbell4** [comment]
This is the commit that broke things: https://github.com/simon-weber/Unofficial-Google-Music-API/commit/64922aabe7a83fa212ecba82373ca7152aab2ebd

**Comment by rjbell4** [comment]
I tried the last version from right before the commit that broke this here: https://github.com/rjbell4/Unofficial-Google-Music-API/tarball/gmusicfs

But that hit this error: The requested URL <code>/music/services/loadalltracks</code> was not found on this server

**Comment by rjbell4** [comment]
To fix this, GMusicFS should switch to the MobileClient, I believe.  There appear to be two pull requests for that alreay at https://github.com/EnigmaCurry/GMusicFS/pulls.

**Comment by rjbell4** [comment]
I received authorization errors with both of the pull requests. :(

**Comment by rjbell4** [comment]
I did get it to work with karlak's port!  I just needed to drop the "0x" in front of the device ID (at least, I think that's what did it).

**Comment by mrdrogdrog** [comment]
how exactly did you fix the problem?

**Comment by grazor** [comment]
Thanks, rjbell4! Your method works fine for me.
I cloned [karlak's repository](https://github.com/karlak/GMusicFS), installed his version:

``` bash
su -c "python setyp.py install"
```

Then discovered my deviceId:

``` bash
gmusicfs --deviceid
```

Removed 0x at beginning and put it to the config file:

```
[credentials]
username = mail@gmail.com
password = password
deviceId = device_id_without_leading_0x
```

**Comment by rjbell4** [comment]
This should be fixed in the latest code now

**Comment by squisher** [comment]
I was getting file listings but couldn't download any files, the verbose log would show a 403 error. Thanks everyone here for the pointer to remove the 0x from the device id - now it is working again!
