### ISSUE TITLE
GMusicFS fails to mount after upgrading gmusicapi to 6.0.0

### ISSUE THREAD

**Issue by thenktor** [EnigmaCurry/GMusicFS#37]
GMusicFS fails to mount after upgrading gmusicapi to 6.0.0:

```
Traceback (most recent call last):
  File "/usr/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/lib64/python2.7/site-packages/gmusicfs/gmusicfs.py", line 476, in main
    fs = GMusicFS(mountpoint, true_file_size=args.true_file_size, verbose=verbosity, scan_library= not args.nolibrary)
  File "/usr/lib64/python2.7/site-packages/gmusicfs/gmusicfs.py", line 240, in __init__
    true_file_size=true_file_size, verbose=verbose, scan=scan_library)
  File "/usr/lib64/python2.7/site-packages/gmusicfs/gmusicfs.py", line 132, in __init__
    self.__login_and_setup(username, password)
  File "/usr/lib64/python2.7/site-packages/gmusicfs/gmusicfs.py", line 176, in __login_and_setup
    self.api.login(username, password)
TypeError: login() takes exactly 4 arguments (3 given)
```

**Comment by thenktor** [comment]
Line 176 in gmusicfs.py should be 
`self.api.login(username, password, deviceId)` 
instead of 
`self.api.login(username, password)`
