### ISSUE TITLE
TabError on startup

### ISSUE THREAD

**Issue by HazWard** [EnigmaCurry/GMusicFS#39]
After a fresh install on GMusicFS with all the dependencies, I get an error when executing `gmusicfs ~/google_music`

The full output of the command is this :

```
Traceback (most recent call last):
  File "/usr/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/gmusicfs/gmusicfs.py", line 95
    if self.library.true_file_size:
                                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by HazWard** [comment]
After changing some lines in `gmusicfs.py` file, I get this error :
(The changes I've made are in my fork)

```
Traceback (most recent call last):
  File "/usr/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 549, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.5/site-packages/gmusicfs/gmusicfs.py", line 412
    print '%s : %s' % (device['name'], device['id'])
                  ^
SyntaxError: invalid syntax
```

**Comment by michael-stevenson** [comment]
@HazWard - I ran into that also.  For me, I switched my active interpreter (gentoo) from python 3.4 -> 2.7 and it did the trick.  Hope that helps.
