### ISSUE TITLE
Changed API of gmusicapi?

### ISSUE THREAD

**Issue by mschlenker** [EnigmaCurry/GMusicFS#44]
INFO:gmusicfs:Logging in...
Traceback (most recent call last):
  File "/usr/local/bin/gmusicfs", line 9, in <module>
    load_entry_point('GMusicFS==0.1', 'console_scripts', 'gmusicfs')()
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 476, in main
    fs = GMusicFS(mountpoint, true_file_size=args.true_file_size, verbose=verbosity, scan_library= not args.nolibrary)
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 240, in **init**
    true_file_size=true_file_size, verbose=verbose, scan=scan_library)
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 132, in **init**
    self.__login_and_setup(username, password)
  File "/usr/local/lib/python2.7/dist-packages/gmusicfs/gmusicfs.py", line 176, in __login_and_setup
    self.api.login(username, password)
**TypeError: login() takes at least 4 arguments (3 given)**

**Comment by Thaelz** [comment]
I got the same error with thunner, that I tried few days ago; if I remember well, the gmusicapi (concerning Webclient) had been modified but the project GMusicFS had no new commits for years, so I recommend you to check a forked one like this one: https://github.com/benklop/GMusicFS

**Comment by KenSharp** [comment]
Neither version works.

**Comment by plumps** [comment]
deviceId is missing in the class. It's not GMusicAPI's fault, but GmusicFS'. To fix it, add deviceId to self.api.login in gmusicfs.py:176 like so
```self.api.login(username, password, deviceId)```
